name: .NET Core
on:
  push:
    branches: [ master, release/** ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    steps:
       - name: Find PR for the Commit
         uses: gauravngandhi/gh-find-current-pr@master
         continue-on-error: true
         if: ${{ github.event_name == 'push' }}
         id: findPr
         with:
           state: all
           
       - name: Echo
         run : |
          pr_info_json=${{ steps.findPr.outputs.pr_info }}
          echo ${{ steps.findPr.outputs.pr_info.user.login }}
          echo ${{ steps.findPr.outputs.title }}
      
       - name: Json Action
         id: format_script
         uses: notiz-dev/github-action-json-property@0.1.0
         with: 
            path: ${{ steps.findPr.outputs.pr_info }}
            prop_path: pr_info.user
            
       - name: Echo
         run : |
          echo ${{ steps.format_script.outputs.prop }}
